name: longboye
version: "0.1.0.0"
category: Web
author: John Evans
maintainer: ops@superpowerscorp.com
copyright: 2017 Superpowers Corp
license: BSD3
github: superpowerscorp/longboye

extra-source-files:
- README.md

ghc-options:
- -Wall
- -Werror

library:
  source-dirs:
  - src
  # damnit.
  - test
  exposed-modules:
  - Longboye
  dependencies:
  - base              >=4.7 && <5
  - Cabal
  - containers
  - directory
  - docopt
  - filepath
  - haskell-src-exts
  - megaparsec
  - protolude
  - safe
  - system-fileio
  - text
  - unix
  # Damnit
  - hspec
  - QuickCheck
  - quickcheck-text

executables:
  longboye:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - longboye

tests:
  longboye-test:
    main: Spec.hs
    source-dirs:
    - src
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - Cabal
    - containers
    - directory
    - filepath
    - longboye
    - protolude
    - haskell-src-exts
    - hspec
    - QuickCheck
    - quickcheck-text
    - safe
    - text
    - unix
