name: longboye
version: '0.1.0.0'
category: Web
author: John Evans
maintainer: ops@superpowerscorp.com
copyright: 2017 Superpowers Corp
license: BSD3
github: superpowerscorp/longboye

extra-source-files:
- README.md

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
  - Longboye
  dependencies:
  - base >=4.7 && <5
  - directory
  - docopt
  - haskell-src-exts
  - megaparsec
  - text
  - safe

executables:
  longboye:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - longboye

tests:
  longboye-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - longboye
